spring:
  thymeleaf:
    cache: false
  config:
    import: application-mysql.yml
  web:
    resources:
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /**
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace
    org.springframework.web : debug
    org.springframework.security: debug



