spring:
  config:
    import:
      application-mysql.yml
#      application-h2.yml

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace
    org.springframework.web : debug
    org.springframework.security: debug

server:
  compression:
    enabled: true # 응답 압축 활성화