spring:
  # h2 ?????? ?? ?? ??
  datasource:
    url : jdbc:h2:mem:test;
    #url: jdbc:h2:tcp://localhost/~/jpashop;
    username : sa
    password :
    driver-class-name: org.h2.Driver

  # jpa ?? ??
  jpa:
    hibernate:
      # ???? ???? ????? ??
      # ?????? ?? ??? ?? ???? ? ??? ?? ???
      ddl-auto: create
    properties:
      hibernate:
        # show_sql : true? System.out?? ?? ??? ?? ??
        # show_sql: true
        format_sql: true

# logging ?? ??
logging:
  level:
    org.hibernate.SQL: debug # hibernate? ??? ?? ??? ???, log? ???
    org.hibernate.type : trace # ?? ????? ?? ? ??? ???