spring:
  thymeleaf:
    cache: false
  config:
    import: application-mysql.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace
    org.springframework.web : debug
    org.springframework.security: debug