INSERT INTO cinema (NAME, LOCATION) VALUES ('가산디지털', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('가양', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('강동', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('건대입구', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('김포공항', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('노원', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('도곡', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('독산', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('브로드웨이(신사)', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('서울대입구', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('수락산', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('수유', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('신도림', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('신림', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('에비뉴엘(명동)', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('영등포', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('용산', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('월드타워', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('은평(롯데몰)', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('중랑', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('청량리', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('합정', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('홍대입구', '서울');
INSERT INTO cinema (NAME, LOCATION) VALUES ('광교아울렛', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('광명(광명사거리)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('광명아울렛', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('광주터미널', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('구리아울렛', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('동탄', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('라페스타', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('마석', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('별내', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('병점', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('부천(신중동역)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('부천역', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('부평', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('부평갈산', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('부평역사', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('북수원(천천동)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('산본피트인', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('서수원', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('성남중앙(신흥역)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('센트럴락', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('송탄', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('수원(수원역)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('수지', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('시화(정왕역)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('시흥장현', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('안산', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('안산고잔', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('안성', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('안양(안양역)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('안양일번가', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('양주고읍', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('영종하늘도시', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('오산(원동)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('용인기흥', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('용인역북', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('위례', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('의정부민락', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('인덕원', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('인천아시아드', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('인천터미널', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('주엽', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('진접', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('파주운정', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('판교(창조경제벨리)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('평촌(범계역)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('평택비전(뉴코아)', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('하남미사', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('향남', '경기/인천');
INSERT INTO cinema (NAME, LOCATION) VALUES ('당진', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대전(백화점)', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대전관저', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대전둔산(월평동)', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대전센트럴', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('서산', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('서청주(아울렛)', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('아산터미널', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('천안불당', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('청주용암', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('충주(모다아울렛)', '충청/대전');
INSERT INTO cinema (NAME, LOCATION) VALUES ('광주(백화점)', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('광주광산', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('군산나운', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('군산몰', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('수완(아울렛)', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('익산모현', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('전주(백화점)', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('전주송천', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('전주평화', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('충장로', '전라/광주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('경주', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('경주황성', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('구미공단', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대구광장', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대구율하', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대구현풍', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('동성로', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('상인', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('상주', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('성서', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('영주', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('영천', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('포항', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('프리미엄구미센트럴', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('프리미엄만경', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('프리미엄안동', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('프리미엄칠곡', '경북/대구');
INSERT INTO cinema (NAME, LOCATION) VALUES ('거창', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('광복', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('김해부원', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('김해아울렛', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('대영', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('동래', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('동부산아울렛', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('마산(합성동)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('부산명지', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('부산본점', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('사천', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('서면(전포동)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('센텀시티', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('양상물금', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('엠비씨네(진주)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('오투(부산대)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('울산(백화점)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('울산성남', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('진주혁신(롯데몰)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('진해', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('창원', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('통영', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('프리미엄경남대', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('프리미엄진주(중안)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('프리미엄해운대(장산역)', '경남/부산/울산');
INSERT INTO cinema (NAME, LOCATION) VALUES ('남원주', '강원');
INSERT INTO cinema (NAME, LOCATION) VALUES ('동해', '강원');
INSERT INTO cinema (NAME, LOCATION) VALUES ('속초', '강원');
INSERT INTO cinema (NAME, LOCATION) VALUES ('원주무실', '강원');
INSERT INTO cinema (NAME, LOCATION) VALUES ('춘천', '강원');
INSERT INTO cinema (NAME, LOCATION) VALUES ('서귀포', '제주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('제주삼화지구', '제주');
INSERT INTO cinema (NAME, LOCATION) VALUES ('제주아라', '제주');

INSERT INTO member (NAME, BIRTHDAY, PHONE, ZIPCODE, STREET, DETAIL, EMAIL, USER_ID, PASSWORD, GENDER, ROLE_NAME)
VALUES ('김용환', '1990-01-01', '010-1111-1111', '06228', '서울특별시 강남구 삼성로 154 (대치동, 강남구의회, 강남구민회관)', '', 'user1@gmail.com', 'user1', 'pw1', 'male', 'USER');
INSERT INTO member (NAME, BIRTHDAY, PHONE, ZIPCODE, STREET, DETAIL, EMAIL, USER_ID, PASSWORD, GENDER, ROLE_NAME)
VALUES ('김용환', '1990-01-01', '010-1111-1112', '06228', '서울특별시 강남구 삼성로 154 (대치동, 강남구의회, 강남구민회관)', '', 'user2@gmail.com', 'user2', 'pw2', 'male', 'MANAGER');
INSERT INTO member (NAME, BIRTHDAY, PHONE, ZIPCODE, STREET, DETAIL, EMAIL, USER_ID, PASSWORD, GENDER, ROLE_NAME)
VALUES ('김용환', '1990-01-01', '010-1111-1113', '06228', '서울특별시 강남구 삼성로 154 (대치동, 강남구의회, 강남구민회관)', '', 'user3@gmail.com', 'user3', 'pw3', 'female', 'ADMIN');

INSERT INTO MOVIE (film_rating, name, runtime) VALUES (15, '올빼미', 150);
INSERT INTO MOVIE (film_rating, name, runtime) VALUES (12, '블랙 팬서: 와칸다 포에버', 120);
INSERT INTO MOVIE (film_rating, name, runtime) VALUES (12, '데시벨', 130);


INSERT INTO THEATER(name, cinema_id) VALUES ('1관', 1);
INSERT INTO THEATER(name, cinema_id) VALUES ('2관', 1);
INSERT INTO THEATER(name, cinema_id) VALUES ('3관', 1);

INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'A', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'A', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'A', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'A', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'A', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'B', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'B', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'B', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'B', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'B', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'C', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'C', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'C', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'C', 1);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'C', 1);

INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'A', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'A', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'A', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'A', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'A', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'B', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'B', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'B', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'B', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'B', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'C', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'C', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'C', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'C', 2);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'C', 2);

INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'A', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'A', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'A', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'A', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'A', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'B', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'B', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'B', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'B', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'B', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('1', 'C', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('2', 'C', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('3', 'C', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('4', 'C', 3);
INSERT INTO SEAT(seat_col, seat_row, theater_id) VALUES ('5', 'C', 3);

INSERT INTO SCREEN(round, start_datetime, movie_id, theater_id) VALUES (1, CURRENT_TIMESTAMP, 1, 1);
INSERT INTO SCREEN(round, start_datetime, movie_id, theater_id) VALUES (1, CURRENT_TIMESTAMP, 2, 2);
INSERT INTO SCREEN(round, start_datetime, movie_id, theater_id) VALUES (1, CURRENT_TIMESTAMP, 3, 3);
INSERT INTO SCREEN(round, start_datetime, movie_id, theater_id) VALUES (2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 120 MINUTE), 3, 3);

INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 1);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 2);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 3);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 4);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 5);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 6);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 7);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 8);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 9);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 10);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 11);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 12);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 13);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 14);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 1, 15);

INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 16);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 17);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 18);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 19);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 20);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 21);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 22);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 23);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 24);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 25);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 26);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 27);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 28);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 29);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 2, 30);

INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 31);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 32);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 33);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 34);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 35);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 36);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 37);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 38);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 39);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 40);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 41);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 42);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 43);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 44);
INSERT INTO SCREEN_SEAT(status, screen_id, seat_id) VALUES ('EMPTY', 3, 45);